name             'vaamo_tmate'
maintainer       'Malte Krupa'
maintainer_email 'malte.krupa@vaamo.de'
license          'All rights reserved'
description      'Installs/Configures tmate'
long_description 'Installs/Configures tmate'
version          '0.1.0'
