name 'vaamo_tmate'
maintainer 'Vaamo Finanz AG'
maintainer_email 'malte.krupa@vaamo.de'
license 'All rights reserved'
description 'Installs/Configures vaamo_tmate'
long_description 'Installs/Configures vaamo_tmate'
version '0.1.0'
depends 'vaamo_default'
depends 'iptables-ng'
